from datetime import datetime

def get_timestamp():
    return datetime.now().strftime(("%y-%m-%d %H:%M:%S"))

Exercise = {
   "exercise_name":"T-pose",
   "exercise_type":"body",
   "reason_stopped":"user_quit",
   "non_impaired_limb_exercise_part":{
      "poses":[
         {
            "ms_since_start":3,
            "pose_data":[
               {
                  "joints":[
                     12,
                     14
                  ],
                  "angle_xy":69,
                  "angle_xz":-69,
                  "angle_yz":0
               },
               {
                  "joints":[
                     11,
                     13
                  ],
                  "angle_xy":70,
                  "angle_xz":-68,
                  "angle_yz":1
               }
            ]
         },
         {
            "ms_since_start":4,
            "pose_data":[
               {
                  "joints":[
                     12,
                     14
                  ],
                  "angle_xy":71,
                  "angle_xz":-68,
                  "angle_yz":0
               },
               {
                  "joints":[
                     11,
                     13
                  ],
                  "angle_xy":70,
                  "angle_xz":-68,
                  "angle_yz":1
               }
            ]
         }
      ]
   },
   "impaired_limb_exercise_part":{
      "poses":[
         {
            "ms_since_start":3,
            "pose_data":[
               {
                  "joints":[
                     12,
                     14
                  ],
                  "angle_xy":69,
                  "angle_xz":-69,
                  "angle_yz":0
               },
               {
                  "joints":[
                     11,
                     13
                  ],
                  "angle_xy":70,
                  "angle_xz":-68,
                  "angle_yz":1
               }
            ]
         },
         {
            "ms_since_start":4,
            "pose_data":[
               {
                  "joints":[
                     12,
                     14
                  ],
                  "angle_xy":71,
                  "angle_xz":-68,
                  "angle_yz":0
               },
               {
                  "joints":[
                     11,
                     13
                  ],
                  "angle_xy":70,
                  "angle_xz":-68,
                  "angle_yz":1
               }
            ]
         }
      ]
   }
}

def read_all():
    return list(Exercise.values())