#swagger.yml

openapi: "3.0.0"
info: 
  title: "REST API ISHA"
  version: "1.0.0"
  description: "Test API for ISHA"

servers:
  - url: "/api"

paths:
  /exercise:
    get:
      operationId: "exercise.read_all"
      tags:
        - "Exercise"
      summary: "Read the list of exercises"
      responses:
        "200":
          description: "Ok"
        "400": 
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
components:
  schemas:
    user:
      type: "object"
      required:
        - id
        - name
      properties:
        id: 
          type: "integer"
        name: 
          type: "string"
    score:
      type: "object"
      required:
        - id
        - exercise_id
        - user_id
        - value
      properties:
        id: 
          type: "integer"
        exercise_id:
          type: "integer"
        user_id:
          type: "integer"
        value: 
          type: "integer"
    exercise:
      type: "object"
      required:
        - id
        - name
        - type
        - description
      properties:
        id: 
          type: "integer"
        name: 
          type: "string"
        type: 
          type: "string"
        description: 
          type: "string"